### ISSUE TITLE
Clarification in the documentation

### ISSUE THREAD

**Issue by larmarange** [guyabel/tidycat#4]
A quick comment. It seems that `tidy_categorical()` is designed only for default contrast (i.e. `contr.treatment()`). With other contrasts, the result is not correct anymore as the estimates do not correspond always to a specific level as you can see with `dummy.coef()`.

Maybe, it should be worth to mention that limitation in the documentation.

Best regards

``` r
library(gtsummary)
library(broom)
library(tidycat)
mod <- glm(response ~ age + grade, trial, family = binomial(link = "logit"), contrasts = list(grade = contr.helmert))
tidy(mod)
#> # A tibble: 4 x 5
#>   term        estimate std.error statistic p.value
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 (Intercept)  -1.68      0.575     -2.92  0.00355
#> 2 age           0.0189    0.0114     1.67  0.0959 
#> 3 grade1       -0.0792    0.198     -0.401 0.688  
#> 4 grade2        0.0309    0.113      0.273 0.785
tidy(mod, conf.int = T) %>%
  tidy_categorical(mod)
#> # A tibble: 5 x 11
#>   term  estimate std.error statistic p.value conf.low conf.high variable level
#>   <chr>    <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl> <chr>    <fct>
#> 1 (Int~  -1.68      0.575     -2.92  0.00355 -2.85      -0.582  (Interc~ (Int~
#> 2 age     0.0189    0.0114     1.67  0.0959  -0.00304    0.0418 age      age  
#> 3 grad~  -0.0792    0.198     -0.401 0.688   -0.471      0.307  grade    I    
#> 4 grad~   0.0309    0.113      0.273 0.785   -0.194      0.251  grade    II   
#> 5 <NA>    0         0          0     0        0          0      grade    III  
#> # ... with 2 more variables: effect <chr>, reference <chr>
dummy.coef(mod)
#> Full coefficients are 
#>                                                    
#> (Intercept):      -1.678002                        
#> age:             0.01893961                        
#> grade:                    I          II         III
#>                  0.04831218 -0.11014759  0.06183541
```

<sup>Created on 2020-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by guyabel** [comment]
Thanks for the notice. I will add the limitation. Sorry for the late reply - I have been swamped with teaching and a little way through trying to fix the issue I wound up finding your [improvments](https://github.com/ggobi/ggally/issues/372) to `ggcoef()` which look amazing - it was the kind of output I had in mind and looks far more flexible than my efforts thus far.  I am going to discontinue improving this package any further with the hope that your work there continues and is fully integrated into GGally.
