### ISSUE TITLE
Levels Don't Match Terms With Rank Deficient Fits

### ISSUE THREAD

**Issue by jared-fowler** [guyabel/tidycat#5]
Hey,

Great package! Just noticed that if I fit a glm where one variable completely describes the other (I think R sometimes calls these rank deficient fits, but not totally sure), then tidycat gets the levels and terms mismatched. Here is an example.

```r
library(magrittr)

# Create collinear data. Feature 1 and Feature 2 are collinear. i.e every level 'B' in feature 2 is a F2 in feature 1
example_data <- base::data.frame(Target = c(0,1,0,1,0,1,1,1,1,0),
                                 Feature1 = as.factor(c('F3', 'F3', 'F2', 'F1', 'F2', 'F1', 'F3', 'F1', 'F2', 'F2')),
                                 Feature2 = as.factor(c('A', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'B', 'B')),
                                 Feature3 = c(0.3, 0.6, 0.4, 0.9, 0.2, 0.6, 0.7, 0.6, 0.9, 0.5),
                                 Feature4 = as.factor(c('Green', 'Green', 'Green', 'Green', 'Green', 'Red', 'Red', 'Red', 'Red', 'Red')))

# build glm
m <- stats::glm('Target ~ Feature1 + Feature2 + Feature3 + Feature4', data=example_data, family = binomial)

# create tidycat table
d <- broom::tidy(m)
tidycat::tidy_categorical(d = d, m = m)
d
```

**Comment by guyabel** [comment]
Thanks. I was trying to fix this issue on and off over the past few weeks but not getting anything close to satisfactory. I think it might be better handled using the development version of [`ggcoef()` ](https://github.com/larmarange/JLutils/blob/master/R/ggcoef_model.R), which is discussed [here](https://github.com/ggobi/ggally/issues/372) - assuming your ultimate aim is to plot the coefficients? As i mentioned in a previous issue, I am not going to continue to develop this package any further as new `ggcoef()` in ggally will most likely be far better.
